force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Multicolour</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Metalic</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/EngineCapacity__c.field-meta.xml
<CustomField>
    <fullName>EngineCapacity__c</fullName>
    <label>Engine capacity</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuranceEndDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceEndDate__c</fullName>
    <label>Insurance end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuranceStartDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceStartDate__c</fullName>
    <label>Insurance start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuredTo__c.field-meta.xml
<CustomField>
    <fullName>InsuredTo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanedTo__c.field-meta.xml
<CustomField>
    <fullName>LoanedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaned to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles (Total loss)</relationshipLabel>
    <relationshipName>Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanStartDate__c.field-meta.xml
<CustomField>
    <fullName>LoanStartDate__c</fullName>
    <label>Loan start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <externalId>true</externalId>
    <label>Registration number</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
            </value>
            <value>
                <fullName>loaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warranty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/YearOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>YearOfVehicle__c</fullName>
    <label>Year of Vehicle</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LWC01_retrieveVehicleDetails.cls
/**
 * @description       : 
 * @author            : Aaliyah Mohungoo
 * @group             : 
 * @last modified on  : 20-11-2022
 * @last modified by  : Aaliyah Mohungoo
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   20-11-2022   Aaliyah Mohungoo   Initial Version
**/
public with sharing class LWC01_retrieveVehicleDetails {
    @AuraEnabled(cacheable=true)
    public static List<Case> CustomerVehicles(Id cusId) {
      List<case> lstcaseOnCustomerVehicle = [
        SELECT
          Id,
          Vehicle__c,
          Vehicle__r.Make__c,
          Vehicle__r.Model__c,
          Vehicle__r.YearOfVehicle__c,
          Vehicle__r.RegistrationNumber__c,
          Vehicle__r.Description__c,
          Vehicle__r.Mileage__c,
          Vehicle__r.Warranty__c,
          Vehicle__r.EngineCapacity__c,
          Vehicle__r.Colour__c,
          Vehicle__r.InsuredTo__c,
          Vehicle__r.InsuranceStartDate__c,
          Vehicle__r.InsuranceEndDate__c                 
        FROM Case
        WHERE Vehicle__c != NULL AND Id=:cusId
      ];
      return lstcaseOnCustomerVehicle;
    }
    @AuraEnabled(cacheable=false)
    public static List<Case> loanVehicles(Id loanId) {
      List<case> lstcaseOnLoanVehicle = [
        SELECT
          Id,
          LoanedVehicle__c,
          LoanedVehicle__r.Make__c,
          LoanedVehicle__r.Model__c,
          LoanedVehicle__r.YearOfVehicle__c,
          LoanedVehicle__r.LoanStartDate__c,
          LoanedVehicle__r.LoanEndDate__c,
          LoanedVehicle__r.LoanedTo__c,
          LoanedVehicle__r.status__c        
        FROM Case
        WHERE LoanedVehicle__c != NULL AND Id=:loanId
      ];
      return lstcaseOnLoanVehicle;
    }
}