force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/isBeingLoaned__c.field-meta.xml
<CustomField>
    <fullName>isBeingLoaned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isBeingLoaned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanStartDate__c.field-meta.xml
<CustomField>
    <fullName>LoanStartDate__c</fullName>
    <label>Loan start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BAT03_getAllVehiclesLoaned.cls
/**
 * @description       :
 * @author            : Aaliyah Mohungoo
 * @group             :
 * @last modified on  : 23-11-2022
 * @last modified by  : Aaliyah Mohungoo
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   23-11-2022   Aaliyah Mohungoo   Initial Version
 **/
global class BAT03_getAllVehiclesLoaned implements Database.Batchable<sObject> {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    // collect the batches of records or objects to be passed to execute

    String query = 'SELECT Id, isBeingLoaned__c, LoanStartDate__c, LoanEndDate__c FROM Vehicle__c WHERE ((LoanStartDate__c <= TODAY AND LoanEndDate__c >= TODAY) AND isBeingLoaned__c = false) OR ((NOT(LoanStartDate__c <= TODAY AND LoanEndDate__c >= TODAY)) AND isBeingLoaned__c = true)';
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<Vehicle__c> vehList) {
    system.debug('>>>>> START the execute method <<<<<');

    for (Vehicle__c veh : vehList) {
      if (
        veh.LoanStartDate__c <= system.TODAY() &&
        veh.LoanEndDate__c >= system.TODAY()
      ) {
        veh.isBeingLoaned__c = true;
      } else {
        veh.isBeingLoaned__c = false;
      }
    }
    try {
      if (vehList.size() > 0) {
        update vehList;
      }
    } catch (Exception e) {
      System.debug(e);
    }
  }

  global void finish(Database.BatchableContext BC) {
    // execute any post-processing operations like sending email
  }
}