force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanStartDate__c.field-meta.xml
<CustomField>
    <fullName>LoanStartDate__c</fullName>
    <label>Loan start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
            </value>
            <value>
                <fullName>loaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LWC01_terminateLoanUS2.cls
/**
 * @description       : 
 * @author            : Aaliyah Mohungoo
 * @group             : 
 * @last modified on  : 18-11-2022
 * @last modified by  : Aaliyah Mohungoo
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   18-11-2022   Aaliyah Mohungoo   Initial Version
**/
public with sharing class LWC01_terminateLoanUS2 {
    @AuraEnabled(cacheable=false)
    public static void removeLoanStatus(Id caseid) {
        List<Case> lstCas = [
            SELECT LoanedVehicle__c,
            LoanedVehicle__r.LoanEndDate__c
            FROM Case
            WHERE Id = :caseid AND LoanedVehicle__c != NULL];
        System.debug('>>>>>>>>>>>>>>>>' + caseid);
        Vehicle__c veh = new Vehicle__c();
        veh.Id = lstCas[0].LoanedVehicle__c;
        veh.status__c = 'available';
        veh.LoanEndDate__c = NULL;
        veh.LoanStartDate__c = NULL;
        update veh;
    }
}